### ISSUE TITLE
Clarify how to use in browser (aka how to "require")

### ISSUE THREAD

**Issue by owencm** [suchipi/fs-remote#1]
Thanks for the work on this!

I followed the readme and tried to get started, but:
```const createClient = require("fs-remote/createClient")```
threw a 'require is not defined' error.

I'm of course now looking into how to solve client-side requiring, but it'd be nice to mention in the readme that require won't work out of the box and giving some pointers for what to do to get this up and running :)

Could help new programmers quickly work out how to get up and running with this!

**Comment by suchipi** [comment]
Good idea!

You can use webpack or browserify to load it in the browser- I will add additional instructions on how to do this.

I'll also create a UMD build so you can include it with a script tag.

**Comment by suchipi** [comment]
Okay, I added some generic webpack/browserify examples to the [examples folder](https://github.com/suchipi/fs-remote/tree/master/examples) and in 0.1.4 we now ship a UMD build that you can load using a script tag; I mention this in the readme.

Thank you for the suggestion!
